### ISSUE TITLE
Needs chunk-loading optimization advices

### ISSUE THREAD

**Issue by nhanledev** [YouHaveTrouble/minecraft-optimization#55]
Hello,

Paper recently merged some optimizations from Tuinity in build #232 , and it affects most of us. (https://github.com/PaperMC/Paper/issues/6413)
Details of `chunk-loading` patch: (https://github.com/PaperMC/Paper/blob/20903fcf5e227a1a03e2afd89f01bfe951b2b328/patches/server/0771-Replace-player-chunk-loader-system.patch)
I hope someone could take a look into the `chunk-loading` settings and find the best way to optimize them.
I am currently having problems with a very delayed chunk loading after update to the new Paper build, on an online server with over 40 players.

**Comment by YouHaveTrouble** [comment]
Those options are not there for server-performance, other than minor I/O and networking boost. The chunk send limits are for clients to not explode because they get too many chunks at once due to starlight being extremely fast.
There are currently no  generalize defaults as they would have to be set according to your view distance, no-tick-view-distance, amount of players, their client side view distance, etc.
It's recommended to try and experiment by yourself to find options that fit your server.
